# Generated by Django 3.2.2 on 2021-05-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_alter_sitesettings_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_link',
            field=models.CharField(default='no', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_link',
            field=models.CharField(default='no', max_length=100),
            preserve_default=False,
        ),
    ]
