# Generated by Django 3.2.2 on 2021-05-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_auto_20210509_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='working_hours',
            field=models.CharField(default='10.00 - 22.00', max_length=30),
            preserve_default=False,
        ),
    ]
