# Generated by Django 3.2.3 on 2021-05-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_delete_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('facebook_link', models.CharField(max_length=100)),
                ('instagram_link', models.CharField(max_length=100)),
                ('working_hours', models.CharField(max_length=30)),
                ('latest_product_amount_in_column', models.IntegerField()),
            ],
        ),
    ]
