# Generated by Django 3.2.2 on 2021-05-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_furniture_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(default='photo_deleted', upload_to='img/category/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
