# Generated by Django 3.2.2 on 2021-05-12 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210508_2349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('category_ordered',)},
        ),
        migrations.AlterModelOptions(
            name='furniture',
            options={'ordering': ('furniture_ordered',)},
        ),
    ]
