# Generated by Django 3.2.2 on 2021-05-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_furniture_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='discount',
            field=models.PositiveIntegerField(default=20),
            preserve_default=False,
        ),
    ]
