# Generated by Django 3.2.3 on 2021-05-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20210516_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(upload_to='img/category'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='photo',
            field=models.ImageField(upload_to='img/furniture'),
        ),
    ]
