# Generated by Django 3.2.2 on 2021-05-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.IntegerField(auto_created=True, verbose_name=2453091767570),
        ),
    ]
