# Generated by Django 3.2.2 on 2021-05-16 22:29

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.BigIntegerField(default=orders.models.Order.random_number),
        ),
    ]
