# Generated by Django 3.2.2 on 2021-05-16 22:42

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default=orders.models.Order.random_number, max_length=20),
        ),
    ]
