# Generated by Django 3.2.2 on 2021-05-16 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='+380505816328', max_length=13),
            preserve_default=False,
        ),
    ]
