# Generated by Django 3.2.2 on 2021-05-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20210517_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='contact_phone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='contact_telegram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='contact_viber',
            field=models.BooleanField(default=False),
        ),
    ]
